# Generated by Django 3.1.7 on 2021-04-27 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_auto_20210423_0002"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="auction_end",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2021, 5, 3, 22, 43, 44, 321218),
                null=True,
            ),
        ),
    ]
