# Generated by Django 3.1.7 on 2022-01-19 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auto_20211227_2220"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credit",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="listing",
            name="auction_end",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2022, 1, 25, 20, 39, 41, 907912),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="cash",
            field=models.IntegerField(default=1000),
        ),
    ]
