# Generated by Django 3.1.7 on 2021-04-23 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_auto_20210422_2319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="auction_end",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2021, 4, 30, 0, 2, 9, 229945),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="active",
            field=models.BooleanField(verbose_name="Watchlist"),
        ),
    ]
