# Generated by Django 3.2.12 on 2022-03-16 00:04

import auctions.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_auction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.FloatField(validators=[auctions.validators.validate_negative_bid], verbose_name='Place Bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='auction_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 23, 0, 4, 59, 307559, tzinfo=utc), null=True),
        ),
    ]
