# Generated by Django 3.2.12 on 2022-04-04 03:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_auction_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credit',
        ),
        migrations.AlterField(
            model_name='listing',
            name='auction_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 11, 3, 35, 42, 885599, tzinfo=utc), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'listing')},
        ),
    ]
