# Generated by Django 3.2.12 on 2022-04-05 04:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20220403_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='auction_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 12, 4, 1, 42, 946351, tzinfo=utc), null=True),
        ),
    ]
