# Generated by Django 3.2.12 on 2022-04-05 04:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_auction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='auction_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 12, 4, 15, 11, 94920, tzinfo=utc), null=True),
        ),
    ]
