# Generated by Django 3.2.12 on 2022-04-06 23:28

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_auction_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='auction_end',
            field=models.DateTimeField(blank=True, default=auctions.models.get_auction_end, null=True),
        ),
    ]
